src/Entity/Image.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ImageRepository")
 * @ORM\HasLifecycleCallbacks
 */
class Image
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $url;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $alt;

    private $file;

    // On ajoute cet attribut pour y stocker le nom du fichier temporairement
    private $tempFilename;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(string $url): self
    {
        $this->url = $url;

        return $this;
    }

    public function getAlt(): ?string
    {
        return $this->alt;
    }

    public function setAlt(string $alt): self
    {
        $this->alt = $alt;

        return $this;
    }
    public function getFile()
    {
        return $this->file;
    }
    public function setFile(UploadedFile $file = null)
    {
        $this->file = $file;

        // On vérifie si on avait déjà un fichier pour cette entité
        if (null !== $this->url) {
            // On sauvegarde l'extension du fichier pour le supprimer plus tard
            $this->tempFilename = $this->url;
    
            // On réinitialise les valeurs des attributs url et alt
            $this->url = null;
            $this->alt = null;
        }
    }


    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function preUpload()
    {
        // Si jamais il n'y a pas de fichier (champ facultatif), on ne fait rien
        if (null === $this->file) {
        return;
        }

        // Le nom du fichier est son id, on doit juste stocker également son extension
        // Pour faire propre, on devrait renommer cet attribut en « extension », plutôt que « url »
        $this->url = $this->file->guessExtension();

        // Et on génère l'attribut alt de la balise <img>, à la valeur du nom du fichier sur le PC de l'internaute
        $this->alt = $this->file->getClientOriginalName();
    }

    /**
     * @ORM\PostPersist()
     * @ORM\PostUpdate()
     */
    public function upload()
    {
      // Si jamais il n'y a pas de fichier (champ facultatif), on ne fait rien
      if (null === $this->file) {
        return;
      }
  
      // Si on avait un ancien fichier, on le supprime
      if (null !== $this->tempFilename) {
        $oldFile = $this->getUploadRootDir().'/'.$this->id.'.'.$this->tempFilename;
        if (file_exists($oldFile)) {
          unlink($oldFile);
        }
      }
      $newNameFile = $this->id.'.'.$this->url;
      $destinationPath = $this->getUploadRootDir(); // Le répertoire de destination
      // On déplace le fichier envoyé dans le répertoire de notre choix
      $this->file->move(
        $destinationPath,
        $newNameFile // Le nom du fichier à créer, ici « id.extension »
      );
    }


  /**
   * @ORM\PreRemove()
   */
  public function preRemoveUpload()
  {
    // On sauvegarde temporairement le nom du fichier, car il dépend de l'id
    $this->tempFilename = $this->getUploadRootDir().'/'.$this->id.'.'.$this->url;
  }

  /**
   * @ORM\PostRemove()
   */
  public function removeUpload()
  {
    // En PostRemove, on n'a pas accès à l'id, on utilise notre nom sauvegardé
    if (file_exists($this->tempFilename)) {
      // On supprime le fichier
      unlink($this->tempFilename);
    }
  }    

    public function getUploadDir()
    {
        // On retourne le chemin relatif vers l'image pour un navigateur (relatif au répertoire /web donc)
        return 'uploads/img';
    }

    public function getWebPath()
    {
      return $this->getUploadDir().'/'.$this->getId().'.'.$this->getUrl();
    }

    protected function getUploadRootDir()
    {
        // On retourne le chemin relatif vers l'image pour notre code PHP
        return __DIR__.'/../../public/'.$this->getUploadDir();
    }

}

src/Form/AdvertType.php
<?php

namespace App\Form;

use App\Entity\Advert;
use App\Form\ImageType;
use App\Form\CategoryType;
use Symfony\Component\Form\FormEvent;
use App\Repository\CategoryRepository;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;

class AdvertType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $pattern = 'I%';
        $builder
            ->add('title',          TextType::class)
            ->add('author',         TextType::class)
            ->add('content',        TextareaType::class)
            // ->add('published',      CheckboxType::class, array('required' => false)  )
            ->add('image',          ImageType::class)
            ->add('categories', EntityType::class, array(
                'class' => 'App\Entity\Category',
                'choice_label' => 'name',
                'multiple' => true,
                'expanded' => true,
                'query_builder' => function(CategoryRepository $repository) use($pattern){
                    return $repository->getLikeQueryBuilder($pattern);
                }
            ))
            ->add('save',           SubmitType::class)
        ;

        $builder->addEventListener(
            FormEvents::PRE_SET_DATA,
            function(FormEvent $event) {
                $advert = $event->getData();

                if (null === $advert) {
                    return;
                }
                if(!$advert->getPublished() || null === $advert->getId()) {
                    $event->getForm()->add('published', checkboxType::class, array('required' => false));
                }
                else {
                    $event->getForm()->remove('published');
                }
            }
        );
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Advert::class,
        ]);
    }
}

src/Controller/AdvertController.php
<?php
// src/Controller/AdvertController.php

namespace App\Controller;

use App\Entity\Image;
use App\Entity\Skill;
use App\Entity\Advert;
use App\Entity\Category;
use App\Form\AdvertType;
use App\Entity\AdvertSkill;
use App\Entity\Application;
use App\Form\AdvertEditType;
use App\Repository\AdvertRepository;
use App\Repository\ApplicationRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\FormType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;

/**
 * @Route("/advert")
 */

class AdvertController extends AbstractController
{
    public function home()
    {
        return $this->redirectToRoute("oc_advert_index");
    }
    /**
     * @Route("/{page}", name="oc_advert_index", requirements={"page" = "\d+"}, defaults={"page" = 1})
     */
    public function index($page)
    {
        if ($page < 1 ) {
            throw $this->createNotFoundException('Page "' .$page. '" inexistante.');
        }
        // Notre liste d'annonce en dur
        // $listAdverts = array(
        //     array(
        //     'title'   => 'Recherche développpeur Symfony',
        //     'id'      => 1,
        //     'author'  => 'Alexandre',
        //     'content' => 'Nous recherchons un développeur Symfony débutant sur Lyon. Blabla…',
        //     'date'    => new \Datetime()),
        //     array(
        //     'title'   => 'Mission de webmaster',
        //     'id'      => 2,
        //     'author'  => 'Hugo',
        //     'content' => 'Nous recherchons un webmaster capable de maintenir notre site internet. Blabla…',
        //     'date'    => new \Datetime()),
        //     array(
        //     'title'   => 'Offre de stage webdesigner',
        //     'id'      => 3,
        //     'author'  => 'Mathieu',
        //     'content' => 'Nous proposons un poste pour webdesigner. Blabla…',
        //     'date'    => new \Datetime())
        // );
        $nbPerPage = 1;
        $listAdverts = $this->getDoctrine()->getRepository(Advert::class)->getAdverts($page, $nbPerPage);

        $nbPages = ceil(count($listAdverts) / $nbPerPage);

        if ($page > $nbPages) {
            throw $this->createNotFoundException('Page "' .$page. '" inexistante.');
        }
        return $this->render("Advert/index.html.twig", ['listAdverts' => $listAdverts,
        'nbPages' => $nbPages,
        'page' => $page ]) ;
    }


    /**
     * @Route("/view/{advert_id}", name="oc_advert_view", requirements={ "advert_id" = "\d+"})
     * @ParamConverter("advert", options={"mapping": {"advert_id": "id"}})
     */

    public function view(Advert $advert)
    {
        // $advert = $this->getDoctrine()
        // ->getRepository(Advert::class)
        // ->find($id);

  
        // if (null === $advert) {
        //     throw new NotFoundHttpException("L'annonce d'id ". $id ." n'existe pas");
        // }

        // On récupère la liste des candidatures de cette annonce
        $listApplications = $this->getDoctrine()
        ->getRepository(Application::class)
        ->findBy(array('advert' => $advert));
        $advertSkills = $this->getDoctrine()->getRepository(AdvertSkill::class)->findBy(
            array('advert' => $advert),
        );
        $image = $this->getDoctrine()->getRepository(Image::class)->findOneBy(
            ["id" => $advert->getImage()->getId() ]
        );
        $advert->setImage($image);
        return $this->render("Advert/view.html.twig", [
            "advert" => $advert,
            "listApplications" => $listApplications,
            "advertSkills" => $advertSkills,
        ]);
    }

    /**
     * @Route("/add", name="oc_advert_add")
     * @Security("has_role('ROLE_AUTEUR')")
     */

    public function add(Request $request)
    {
        // if (!$this->get('security.authorization_checker')->isGranted("ROLE_AUTEUR")) {
        //     throw new AccessDeniedException('Accès limité aux auteurs.');
        // }
        $advert = new Advert();
        $form = $this->createForm(AdvertType::class, $advert);
      

        if ($request->isMethod('POST')) {
            //Link form and request
            $form->handleRequest($request);
            if ($form->isValid()) {
                //$advert->getImage()->upload();
                $em = $this->getDoctrine()->getManager();
                $em->persist($advert);
                $em->flush();
            }
            $this->addFlash('notice', 'Annonce bien enregistrée');
            return $this->redirectToRoute('oc_advert_view', [
                'advert_id' => $advert->getId()
            ]);
        }

        return $this->render("Advert/add.html.twig", 
        ['form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/edit/{id}", name="oc_advert_edit", requirements={"id" = "\d+"})
     */

    public function edit($id, Request $request)
    {
        $advert = $this->getDoctrine()->getManager()->getRepository(Advert::class)
        ->find($id);
        
        if ( null === $advert) {
            throw new NotFoundHttpException("L'annonce d'id ".$id." n'existe pas");
        }

        $form = $this->get("form.factory")->create(AdvertEditType::class, $advert);

        if ($request->isMethod('POST') && $form->handleRequest($request)->isValid()) {
            $this->getDoctrine()->getManager()->flush();
            $this->addFlash("notice", "Annonce bien modifiée.");
            return $this->redirectToRoute("oc_advert_view", [
                'advert_id' => $advert->getId(),
            ]);
        }

        return $this->render('Advert/edit.html.twig', ['advert' => $advert,
        'form' => $form->createView(),
        ]);
    }

     /**
      * @Route("/delete/{id}", name="oc_advert_delete", requirements={"id" = "\d+"})
      */

    public function delete($id, Request $request)
    {
        $em = $this->getDoctrine()->getManager();

        $advert = $em->getRepository(Advert::class)->find($id);
    
        if (null === $advert) {
          throw new NotFoundHttpException("L'annonce d'id ".$id." n'existe pas.");
        }
    
        //create empty form which content csrf field

        $form = $this->get('form.factory')->create();

        if ($request->isMethod("POST") && $form->handleRequest($request)->isValid()) {
            $em->remove($advert);
            $em->flush();

            $this->addFlash('info', "L'annonce a été bien supprimée");

            return $this->redirectToRoute("oc_advert_index");
        }
    
        return $this->render("Advert/delete.html.twig", array(
            'advert' => $advert,
            'form' => $form->createView(),
        ));
    }
      
    public function menu($limit)
    {
        // On fixe en dur une liste ici, bien entendu par la suite
        // on la récupérera depuis la BDD !
        // $listAdverts = array(
        // array('id' => 2, 'title' => 'Recherche développeur Symfony'),
        // array('id' => 5, 'title' => 'Mission de webmaster'),
        // array('id' => 9, 'title' => 'Offre de stage webdesigner')
        // );
        // $em = $this->getDoctrine()->getManager();
        $listAdverts = $this->getDoctrine()->getRepository(Advert::class)->findAll();

        return $this->render('Advert/menu.html.twig', array(
        // Tout l'intérêt est ici : le contrôleur passe
        // les variables nécessaires au template !
        'listAdverts' => $listAdverts
        ));
    }

    public function contact()
    {
        return $this->redirectToRoute("oc_advert_index");
    }

}

templates/Advert/add.html.twig
{# templates/Advert/add.html.twig #}

{% extends "Advert/layout.html.twig" %}

{% block title %}
  Ajouter une annonce - {{ parent() }}
{% endblock %}

{% block ocplatform_body %}

  <h2>Ajouter une annonce</h2>

  {{ include("Advert/form.html.twig") }}

  <p>
    Vous ajoutez une annonce, merci de ne pas changer
    l'esprit général de l'annonce déjà publiée.
  </p>

  <p>
    <a href="{{ path('oc_advert_index') }}" class="btn btn-default">
      <i class="glyphicon glyphicon-chevron-left"></i>
      Retour à l'accueil
    </a>
  </p>

{% endblock %}

templates/Advert/delete.html.twig
{% extends "Advert/layout.html.twig" %}

{% block title %}
  Supprimer une annonce - {{ parent() }}
{% endblock %}

{% block ocplatform_body %}

  <h2>Supprimer une annonce</h2>

  <p>
    Etes-vous certain de vouloir supprimer l'annonce "{{ advert.title }}" ?
  </p>

  {# On met l'id de l'annonce dans la route de l'action du formulaire #}
  <form action="{{ path('oc_advert_delete', {'id': advert.id}) }}" method="post">
    <a href="{{ path('oc_advert_view', {'advert_id': advert.id}) }}" class="btn btn-default">
      <i class="glyphicon glyphicon-chevron-left"></i>
      Retour à l'annonce
    </a>
    {# Ici j'ai écrit le bouton de soumission à la main #}
    <input type="submit" value="Supprimer" class="btn btn-danger" />
    {# Ceci va générer le champ CSRF #}
    {{ form_rest(form) }}
  </form>

{% endblock %}

templates/Advert/edit.html.twig
{# templates/Advert/edit.html.twig #}

{% extends "Advert/layout.html.twig" %}

{% block title %}
  Modifier une annonce - {{ parent() }}
{% endblock %}

{% block ocplatform_body %}

  <h2>Modifier une annonce</h2>

  {{ include("Advert/form.html.twig") }}

  <p>
    Vous éditez une annonce déjà existante, merci de ne pas changer
    l'esprit général de l'annonce déjà publiée.
  </p>

  <p>
    <a href="{{ path('oc_advert_view', {advert_id: advert.id}) }}" class="btn btn-default">
      <i class="glyphicon glyphicon-chevron-left"></i>
      Retour à l'annonce
    </a>
  </p>

{% endblock %}

templates/Advert/form.html.twig
{# templates/Advert/form.html.twig #}
<h3>Formulaire d'annonce</h3>

<div class="well">
  {{ form_start(form, {'attr': {'class': 'form-horizontal'}}) }}

  {# Les erreurs générales du formulaire. #}
  {{ form_errors(form) }}

  {# Génération du label + error + widget pour un champ. 
  {{ form_row(form.date) }}#}

  {# Génération manuelle et éclatée : #}
  <div class="form-group">
    {# Génération du label. #}
    {{ form_label(form.title, "Titre de l'annonce", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}

    {# Affichage des erreurs pour ce champ précis. #}
    {{ form_errors(form.title) }}

    <div class="col-sm-10">
      {# Génération de l'input. #}
      {{ form_widget(form.title, {'attr': {'class': 'form-control'}}) }}
    </div>
  </div>

  {# Idem pour un autre champ. #}
  <div class="form-group">
    {{ form_label(form.content, "Contenu de l'annonce", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}
    {{ form_errors(form.content) }}
    <div class="col-sm-10">
      {{ form_widget(form.content, {'attr': {'class': 'form-control'}}) }}
    </div>
  </div>

  <div class="form-group">
    {{ form_label(form.author, "Auteur de l'annonce", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}
      {{ form_errors(form.author) }}
      <div class="col-sm-10">
        {{ form_widget(form.author, {'attr': {'class': 'form-control'}}) }}
      </div>
  </div>

  {{ form_row(form.categories) }}
  <a href="#" id="add_category" class="btn btn-default">Add category</a>

  {# Pour le bouton, pas de label ni d'erreur, on affiche juste le widget #}
  {{ form_widget(form.save, {'attr': {'class': 'btn btn-primary'}}) }}

  {# Génération automatique des champs pas encore écrits.
     Dans cet exemple, ce serait le champ CSRF (géré automatiquement par Symfony !)
     et tous les champs cachés (type « hidden »). #}
  {{ form_rest(form) }}

  {# Fermeture de la balise <form> du formulaire HTML #}
  {{ form_end(form) }}
</div>


{# On charge la bibliothèque jQuery. Ici, je la prends depuis le CDN google
   mais si vous l'avez en local, changez simplement l'adresse. #}
{# <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script> #}

{# Voici le script en question : #}
<script type="text/javascript">
  $(document).ready(function() {
    // On récupère la balise <div> en question qui contient l'attribut « data-prototype » qui nous intéresse.
    var $container = $('div#advert_categories');

    // On définit un compteur unique pour nommer les champs qu'on va ajouter dynamiquement
    var index = $container.find(':input').length;

    // On ajoute un nouveau champ à chaque clic sur le lien d'ajout.
    $('#add_category').click(function(e) {
      addCategory($container);

      e.preventDefault(); // évite qu'un # apparaisse dans l'URL
      return false;
    });

    // On ajoute un premier champ automatiquement s'il n'en existe pas déjà un (cas d'une nouvelle annonce par exemple).
    if (index == 0) {
      addCategory($container);
    } else {
      // S'il existe déjà des catégories, on ajoute un lien de suppression pour chacune d'entre elles
      $container.children('div').each(function() {
        addDeleteLink($(this));
      });
    }

    // La fonction qui ajoute un formulaire CategoryType
    function addCategory($container) {
      // Dans le contenu de l'attribut « data-prototype », on remplace :
      // - le texte "__name__label__" qu'il contient par le label du champ
      // - le texte "__name__" qu'il contient par le numéro du champ
      var template = $container.attr('data-prototype')
        .replace(/__name__label__/g, 'Catégorie n°' + (index+1))
        .replace(/__name__/g,        index)
      ;

      // On crée un objet jquery qui contient ce template
      var $prototype = $(template);

      // On ajoute au prototype un lien pour pouvoir supprimer la catégorie
      addDeleteLink($prototype);

      // On ajoute le prototype modifié à la fin de la balise <div>
      $container.append($prototype);

      // Enfin, on incrémente le compteur pour que le prochain ajout se fasse avec un autre numéro
      index++;
    }

    // La fonction qui ajoute un lien de suppression d'une catégorie
    function addDeleteLink($prototype) {
      // Création du lien
      var $deleteLink = $('<a href="#" class="btn btn-danger">Supprimer</a>');

      // Ajout du lien
      $prototype.append($deleteLink);

      // Ajout du listener sur le clic du lien pour effectivement supprimer la catégorie
      $deleteLink.click(function(e) {
        $prototype.remove();

        e.preventDefault(); // évite qu'un # apparaisse dans l'URL
        return false;
      });
    }
  });
</script>

templates/Advert/home.html.twig
{% extends "Advert/layout.html.twig" %}

{% block body %}
    {% for mess in app.flashes("message") %}

        <div class="alert alert-info"> <p>{{ mess }}</p> </div>

    {% endfor %}
{% endblock %}

templates/Advert/index.html.twig
{# templates/Advert/index.html.twig #}

{% extends "Advert/layout.html.twig" %}

{% block title %}
  Accueil - {{ parent() }}
{% endblock %}

{% block ocplatform_body %}

  <h2>Liste des annonces</h2>

  <ul>
    {% for advert in listAdverts %}
      <li>
        <a href="{{ path('oc_advert_view', {'advert_id': advert.id}) }}">
          {{ advert.title }}
        </a>
        par {{ advert.author }},
        le {{ advert.date|date('d/m/Y') }}
      </li>
    {% else %}
      <li>Pas (encore !) d'annonces</li>
    {% endfor %}
  </ul>

  <ul class="pagination">
  {# On utilise la fonction range(a, b) qui crée un tableau de valeurs entre a et b #}
  {% for p in range(1, nbPages) %}
    <li{% if p == page %} class="active"{% endif %}>
      <a href="{{ path('oc_advert_index', {'page': p}) }}">{{ p }}</a>
    </li>
  {% endfor %}
</ul>

{% endblock %}

templates/Advert/layout.html.twig
{# templates/Advert/layout.html.twig #}

{% extends 'base.html.twig' %}

{% block title %}
  Annonces - {{ parent() }}
{% endblock %}

{% block body %}

  {# On définit un sous-titre commun à toutes les pages du bundle, par exemple #}
  <h1>Annonces</h1>

  <hr>

  {# On définit un nouveau bloc, que les vues du bundle pourront remplir #}
  {% block ocplatform_body %}
  {% endblock %}

{% endblock %}

templates/Advert/menu.html.twig
{# templates/Advert/menu.html.twig #}

<ul class="nav nav-pills nav-stacked">
  {% for advert in listAdverts %}
    <li>
      <a href="{{ path('oc_advert_view', {'advert_id': advert.id}) }}">
        {{ advert.title }}
      </a>
    </li>
  {% endfor %}
</ul>

templates/Advert/view.html.twig
{# src/OC/PlatformBundle/Resources/view/Advert/view.html.twig #}

{% extends "Advert/layout.html.twig" %}

{% block title %}
  Lecture d'une annonce - {{ parent() }}
{% endblock %}

{% block ocplatform_body %}

  {# On vérifie qu'une image soit bien associée à l'annonce #}
  {% if advert.image is not null %}
    {# <img src="{{ advert.image.url }}" alt="{{ advert.image.alt }}"> #}
    {# <img
  src="{{ asset(advert.image.uploadDir ~ '/' ~ advert.image.id ~ '.' ~ advert.image.url) }}"
  alt="{{ advert.image.alt }}"
/> #}

    <img 
      src="/{{ advert.image.webPath }}"
      alt="{{ advert.image.alt }}"
    />  
  {% endif %}

  <h2>{{ advert.title }}</h2>
  <i>Par {{ advert.author }}, le {{ advert.date|date('d/m/Y') }}</i>

  <div class="well">
    {{ advert.content }}
  </div>
  <div class="application">
    <h2>Candidatures liées à cet annonce</h2>
    {% for application in listApplications %}

        <i> Par {{ application.author }},
        le {{ application.date|date("d/m/Y") }} </i>
        <div class="well"> {{ application.content }} </div>

    {% endfor %}
  </div>

  <p>
    <a href="{{ path('oc_advert_index') }}" class="btn btn-default">
      <i class="glyphicon glyphicon-chevron-left"></i>
      Retour à la liste
    </a>
    <a href="{{ path('oc_advert_edit', {'id': advert.id}) }}" class="btn btn-default">
      <i class="glyphicon glyphicon-edit"></i>
      Modifier l'annonce
    </a>
    <a href="{{ path('oc_advert_delete', {'id': advert.id}) }}" class="btn btn-danger">
      <i class="glyphicon glyphicon-trash"></i>
      Supprimer l'annonce
    </a>
  </p>

{% endblock %}